import type { Metadata } from "next";
import { Heebo, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], display: "swap", variable: '--font-Inter', });
const heebo = Heebo({ subsets: ['latin'], display: "swap", variable: '--font-Heebo', });


export const metadata: Metadata = {
  title: "NextJS Stack Overflow Test.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
          <body className={`${inter.variable} ${heebo.variable} font-Inter`}>{children}</body>
      </html>
  );
}
